/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChessBoard */

#ifndef _Included_ChessBoard
#define _Included_ChessBoard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChessBoard
 * Method:    initializeBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChessBoard_initializeBoard
  (JNIEnv *, jobject);

/*
 * Class:     ChessBoard
 * Method:    getBoardState
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_ChessBoard_getBoardState
  (JNIEnv *, jobject);

/*
 * Class:     ChessBoard
 * Method:    movePiece
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_ChessBoard_movePiece
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     ChessBoard
 * Method:    isCheckmate
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_ChessBoard_isCheckmate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     ChessBoard
 * Method:    isWhiteTurn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ChessBoard_isWhiteTurn
  (JNIEnv *, jobject);

/*
 * Class:     ChessBoard
 * Method:    isInCheck
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ChessBoard_isInCheck
  (JNIEnv *, jobject);

/*
 * Class:     ChessBoard
 * Method:    setBoardState
 * Signature: ([[IZ)V
 */
JNIEXPORT void JNICALL Java_ChessBoard_setBoardState
  (JNIEnv *, jobject, jobjectArray, jboolean);

/*
 * Class:     ChessBoard
 * Method:    isStalemate
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_ChessBoard_isStalemate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     ChessBoard
 * Method:    getCurrentScore
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_ChessBoard_getCurrentScore
  (JNIEnv *, jobject);

/*
 * Class:     ChessBoard
 * Method:    promotePawn
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ChessBoard_promotePawn
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
